
try {
    var a = 5;
    var b = "hola";
    console.log("antes del calculo");
    console.log(a*c);
    console.log("final del programa");
}catch(e){
    console.log("ocurrio un error en el calculo");
}finally{
    console.log("siempre voy a ejecutar");
}
console.log("fuera del try");

